### ISSUE TITLE
Add app to fdroid?

### ISSUE THREAD

**Issue by maloo1** [Sanmeet007/logger#11]
Hi,
I found your app by browsing github and its really helpful! Thanks!!

Do you think it could be added to Fdroid?
I believe this will open it up to many more users:)

**Comment by Sanmeet007** [comment]
Hi @maloo1,

Thank you so much for using my app and for your kind words! I really appreciate the support. I'll definitely work on adding the app directly to F-Droid. In the meantime, you can already find it in the [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.logger.app/) F-Droid repo.

Thanks again!

**Comment by Sanmeet007** [comment]
Hi @maloo1 ,

I'm thrilled to share that the app is now officially available on F-Droid! 🎉 This means it’s no longer exclusive to the IzzyOnDroid repo.

A big thank you to IzzySoft for their incredible support during the earlier stages of the app's journey. Their help was invaluable, and I’m truly grateful for it.

Thank you for your patience and support as well—I hope this makes the app even more accessible to everyone!

Best regards,
Sanmeet

**Comment by maloo1** [comment]
Thanks Sanmeet!! I feel this will mean your great app will help more people out:) And also thanks to IzzyOnDroid for providing an awesome service too

**Comment by Sanmeet007** [comment]
Welcome @maloo1! 🎉 Though my app will be available to download from F-Droid starting December 10! (Phew, the build process & new app listing takes 7 days, thanks to the F-Droid team.) Can't wait! 🚀
