### ISSUE TITLE
System locale time ( 12/24 Hrs format )

### ISSUE THREAD

**Issue by Sanmeet007** [Sanmeet007/logger#14]
Hello @Sanmeet007

Is it possible for the app to honor system locale settings?
App shows 12 hour clock despite system using 24-hour. g
Or maybe you can make it an in-app setting?

_Originally posted by @nev3rfail in https://github.com/Sanmeet007/logger/issues/4#issuecomment-2396009888_

**Comment by nev3rfail** [comment]
Tell me if I can help with any additional info.

Android 11; AOSP.
Locale that problem occurs with: English (UK);
Notes: app ignores both the system locale and the 24 hour force switch (might be good for testing -- set the phone to English (US) and then just flip the switch to get 12/24h clock)

Thank you for your quick reaction :)

**Comment by Sanmeet007** [comment]
Hi @nev3rfail ,

Thanks again for spotting this bug and for your detailed input! I’ll be fixing this in the next version. By default, the app will now follow the phone's current time format, whether it's 12-hour or 24-hours.

Additionally, I’ll add an in-app dropdown option where you can manually select the time format for the application itself:
- System Default (default)
- 24-hour format
- 12-hour format

This will give more flexibility and allow users to switch formats easily. I appreciate your feedback and will notify you when the update is live.

Thanks a lot for reporting  :-) 
Please wait for next update ...

**Comment by Sanmeet007** [comment]
Hey @nev3rfail ,

I have successfully fixed this issue! You can download the latest version of the [app](https://github.com/Sanmeet007/logger/releases/tag/v2.4.1).

To use the 24-hour format on Android, go to:

**Settings** > **Date and time** > Enable **Use 24-hour format**

(The settings might differ, but it's generally like the above : Samsung phones )

![Screenshot_20241008_013132_Settings](https://github.com/user-attachments/assets/3a7f8411-ee39-4b05-b495-45144385451a)

**Comment by nev3rfail** [comment]
Thanks a ton. Works like a charm. 

May I suggest that you add a "call" feature to the log so user can click some button to call user from the log? I'd then be using this app instead of the default aosp's Calls application :)

**Comment by Sanmeet007** [comment]
Hey @nev3rfail ,

Thanks for the awesome suggestion! I totally get where you're coming from, but the app is primarily built for call log analysis, importing, and exporting. Features like direct calling (or call recording)  are probably better suited for other apps designed specifically for that.

My goal is to keep the app focused on making call logs easily accessible and simple to manage. However, I think your idea is super interesting, and it's definitely something I’d love to explore in the future!

Also, you can easily place a call for a specific log by swiping from left to right on the call log and then hitting Call (swipe gesture). A simple image is attached to guide you!

![Group 82](https://github.com/user-attachments/assets/f9e56fe0-1937-4711-b6c8-445c6d48f670)

Appreciate your feedback!
