### ISSUE TITLE
[feature request] SIM filter

### ISSUE THREAD

**Issue by GGORG0** [Sanmeet007/logger#15]
I use dual SIM. Could you please add a filter for the SIM?

Awesome app by the way, good work!

**Comment by Sanmeet007** [comment]
Hi @GGORG0 ,

Thank you so much for using Logger and for your valuable feedback! I’m glad to hear you're finding the app useful.

I’d be happy to build a feature that allows you to filter call logs by SIM card. This is a great idea, and I can see how it would enhance the app’s usability for dual SIM users.

Please note that this will take some time to implement and thoroughly test, so I appreciate your patience while I work on it. You can expect this feature in one of the upcoming updates.

Thanks again for your support!

**Comment by GGORG0** [comment]
I appreciate your quick response and am looking forward to the feature getting implemented! Thanks!
