### ISSUE TITLE
Include total time?

### ISSUE THREAD

**Issue by sphh** [Sanmeet007/logger#17]
In the `Analytics` tab, the average and longest call duration are shown. Could you please also show the total time (sum of all call times), the outgoing and incoming call times? This might be especially helpful, if you have a call time package and want to check, how much time you have already used.

**Comment by Sanmeet007** [comment]
Hi @sphh  , 
You can checkout how much time you spent on calls using filters and 


![Group 235](https://github.com/user-attachments/assets/b6174fa8-2464-4ea8-b125-0c87cd522c4a)
![Group 236](https://github.com/user-attachments/assets/7a87c7e2-3243-48a0-a23d-38bbc24c432a)

**Comment by Sanmeet007** [comment]
@sphh You can use the filters to select the call type (outgoing or incoming), and voilà! You'll get the total call durations for each type.

![image](https://github.com/user-attachments/assets/1bc60611-8735-47ae-a667-b0af8e3ae393)

**Comment by sphh** [comment]
Yes, that's possible. But IMHO cumbersome in the current implementation (a log of clicks required to see that information). Personally I would very much prefer
1. A piechart similar to that one with the number of calls, which is already implemented.
2. Extending the section `Call Duration` with information similar to those in `Call Statistics`, but with the call durations instead of the number of calls, e.g. it could contain the following tiles:
    1. Outgoing Calls (time)
    2. Incoming Calls (time) 
    3. Average Outgoing (time)
    4. Longest Outgoing (time)
    5. Average Incoming (time)
    6. Longest Incoming (time)
    7. Total (time)
 
But that might already be an overkill?

Three other trains of thoughts (that might also be an overkill): 
1. Make the information displayed in the `Analytics` tab configurable.
2. Add a drop-down menu to the `Analytics` tab containing saved configurations to quickly switch between different views. For each of these views the filter (and if possible the information displayed as mentioned in 1.) are saved together with a name. It is then possible to quickly switch between different information views. For me that would the all-dancing-all-singing implementation.
3. Make the tab, which is displayed, when starting the app, configurable:
    1. Select a fixed tab: `Logs`, `Analytics` (or `Analytics with view from 2.)
    2. Last opened tab.

What do you think?

**Comment by Sanmeet007** [comment]
Hi @sphh,

Wow, you’ve got a lot of great ideas here—I truly appreciate the thought you’ve put into it!

A customizable Analytics tab is an intriguing idea and could add a lot of flexibility for users. That said, it would require significant development and testing, so while I can’t guarantee it right now, it’s definitely something I’d love to explore in the future.

For now, I’ll keep these suggestions in mind as I continue to improve the app. Thanks again for sharing your insights—it’s always inspiring to hear creative feedback like this! 😊

Nice thoughts, by the way!
