### ISSUE TITLE
GUI problems on tiny phones

### ISSUE THREAD

**Issue by sphh** [Sanmeet007/logger#18]
Please have a look at the following screenshots:

### Settings tab:
![Screenshot_20241211-134757](https://github.com/user-attachments/assets/f7965724-9c0e-49a9-92b2-85aceff900f9) ![Screenshot_20241211-134803](https://github.com/user-attachments/assets/44c85383-e247-4054-b16e-ba44beaf980e)

### Analytics tab
![Screenshot_20241211-134342](https://github.com/user-attachments/assets/c7160576-79f6-466c-97b7-f67d89e90500)

Could this be improved for tiny phones (mine has a screen with just 240x432 pixels, a Unihertz Jelly Pro)?

Finally:
### Logs tab
![Screenshot_20241211-134846](https://github.com/user-attachments/assets/7cf0f3d2-4d2e-469f-b68e-f1a2d8589949)

Here the phone number breaks into a new line and each entry needs a lot of vertical space. Could this be improved, so that each tile does not take up so much vertical space? Thanks!

**Comment by Sanmeet007** [comment]
Hi @sphh,

Thank you for bringing this to my attention! I appreciate your detailed feedback about the responsiveness on small screen devices. I'll work on optimizing the layout to reduce vertical space and improve the overall experience for such screens.

These improvements will be included in the next update. Thanks for your patience and support!

**Comment by Sanmeet007** [comment]
Hi again @sphh!  

Thanks for your patience. I've just released [v2.6.1](https://github.com/Sanmeet007/logger/releases/tag/v2.6.1), where the UI has been improved for small screen devices along with some bug fixes.  

I truly apologize for the less-than-ideal initial experience and hope the updates make the app much more enjoyable for you. A lot of effort and passion goes into building this, and your feedback means the world to me! Let me know if there's anything else I can improve.  

Cheers,  
Sanmeet 😊

**Comment by sphh** [comment]
I'm looking forward to see this new version on F-Droid! :tada:
