### ISSUE TITLE
Mixed translation 

### ISSUE THREAD

**Issue by Stzyxh** [Sanmeet007/logger#21]
In my settings i have german as language.
But only a few strings are translated. That is no problem but the other strings are french. ![Screenshot_20241228-095830.png](https://github.com/user-attachments/assets/53ce4e5b-370f-44f0-8efb-3a27e9735c7a)

Version: 2.7
Android-version: 13
Phone: Fairphone 4

**Comment by Sanmeet007** [comment]
Hi @Stzyxh,

Thank you so much for pointing this out! I don't really know German or any languages other than English and regional Indian languages, so your feedback is incredibly helpful. I would be really grateful if you could point out which specific values are incorrect. This will not only help me but also assist others.

For your reference, here is the file responsible for translations in German:  
German Translations : https://github.com/Sanmeet007/logger/blob/main/lib/l10n/app_de.arb

And here's the English file for comparison:  
English Translations: https://github.com/Sanmeet007/logger/blob/main/lib/l10n/app_en.arb

Thanks again for your help! I know I'm asking a lot, but it would really mean the world to me.

**Comment by Stzyxh** [comment]
> Hi @Stzyxh,
> 
> Thank you so much for pointing this out! I don't really know German or any languages other than English and regional Indian languages, so your feedback is incredibly helpful. I would be really grateful if you could point out which specific values are incorrect. This will not only help me but also assist others.
> 
> For your reference, here is the file responsible for translations in German: German Translations : https://github.com/Sanmeet007/logger/blob/main/lib/l10n/app_de.arb
> 
> And here's the English file for comparison: English Translations: https://github.com/Sanmeet007/logger/blob/main/lib/l10n/app_en.arb
> 
> Thanks again for your help! I know I'm asking a lot, but it would really mean the world to me.

_The most strings are spanish and some are german
This is the correct order so the first part of the file is all spanish and a small little part at the end is german._





{
   "aboutText": "Acerca de",
    "advancedSettingsLabelText": "Ajustes Avanzados",
    "analyticsPolicyLabelText": "Política de Analítica",
    "analyticsPolicyText": "Todos los datos del registro de llamadas se analizan localmente en tu dispositivo y nunca se transmiten a servidores en línea, lo que garantiza tu privacidad y mantiene tu información segura y confidencial",
    "analyticsScreenLabelText": "Analítica",
    "appError": "¡Vaya! Algo salió mal",
    "appTitle": "Logger",
    "applyFiltersText": "Aplicar Filtros",
    "baseGhostErrorMessage": "Algo salió mal",
    "baseSettingsLabelText": "Ajustes Generales",
    "blockedText": "Bloqueado",
    "callLogsExportFailureText": "¡Error al descargar el archivo!",
    "callLogsExportFormatLabelText": "Formato de exportación de registros de llamadas",
    "callLogsExportSuccessText": "Registros de llamadas extraídos y descargados correctamente",
    "callTypeText": "Tipo de Llamada",
    "cancelText": "Cancelar",
    "configureText": "Configurar",
    "confirmImportLabelText": "Confirmar Inicio de Importación",
    "confirmImportText": "Importar registros de llamadas es una tarea significativa que puede dañar irreversiblemente tus registros actuales, sobrescribir datos y causar inconsistencias en tu historial. Ten en cuenta que este proceso puede llevar algún tiempo y podría provocar los problemas mencionados anteriormente. Procede con precaución.",
    "continueText": "Continuar",
    "dateText": "Fecha",
    "disableLogsSharingText": "Deshabilitar el uso compartido del registro de llamadas",
    "donateText": "Donar",
    "downloadConfirmationText": "¿Estás seguro de que quieres descargar tus registros de llamadas en formato {currentImportType}? Esta acción guardará tu historial de llamadas en un archivo {currentImportType} en tu dispositivo.",
    "downloadText": "Descargar",
    "dtAAcronymExapandedText": "Nombre completo del día de la semana",
    "dtBAcronymExapandedText": "Nombre completo del mes",
    "dtHAcronymExapandedText": "Hora en formato de 24 horas",
    "dtIAcronymExapandedText": "Hora en formato de 12 horas",
    "dtMAcronymExapandedText": "Minutos",
    "dtSAcronymExapandedText": "Segundos",
    "dtUAcronymExapandedText": "Número de semana del año (domingo como primer día de la semana)",
    "dtWAcronymExapandedText": "Número de semana del año (lunes como primer día de la semana)",
    "dtXAcronymExapandedText": "Representación de la hora",
    "dtYAcronymExapandedText": "Año con siglo",
    "dtZAcronymExapandedText": "Nombre de la zona horaria",
    "dtaAcronymExapandedText": "Nombre abreviado del día de la semana",
    "dtbAcronymExapandedText": "Nombre abreviado del mes",
    "dtcAcronymExapandedText": "Representación de la fecha y la hora",
    "dtdAcronymExapandedText": "Día del mes",
    "dtfAcronymExapandedText": "Milisegundos",
    "dtjAcronymExapandedText": "Día del año",
    "dtmAcronymExapandedText": "Mes como número",
    "dtpAcronymExapandedText": "Indicador AM/PM",
    "dtxAcronymExapandedText": "Representación de la fecha",
    "dtyAcronymExapandedText": "Año sin siglo",
    "dtzAcronymExapandedText": "Desplazamiento de la zona horaria desde UTC",
    "durationText": "Duración",
    "enableCallDurationFilteringText": "Habilitar el filtrado por duración",
    "enableCallLogCountVisibilityText": "Mostrar el recuento de registros de llamadas",
    "enableFilterByAccountIdText": "Habilitar filtro por ID de cuenta",
    "exploreNowText": "Explorar ahora",
    "exploreProjectButtonText": "Explorar Proyecto en Github",
    "exportFileNameFormatLabelText": "Formato del nombre de archivo de exportación",
    "filenameFormatHintText": "mis-registros-de-llamadas-[%token]",
    "filenameFormatLabelText": "Formato del nombre de archivo",
    "filterText": "Filtrar",
    "getStartedText": "Comenzar",
    "ghostErrorMessage": "Hmm. Algo salió mal",
    "hideText": "Ocultar",
    "hintMobileNumberText": "9XXX XXXX",
    "importCallLogsText": "Importar tus registros de llamadas",
    "incomingText": "Entrante",
    "logsScreenLabelText": "Registros",
    "maximumDurationHintText": "ej: 60",
    "maximumDurationLabelText": "Mín. (en segs)",
    "minimumDurationHintText": "ej: 0",
    "minimumDurationLabelText": "Mín. (en segs)",
    "missedText": "Perdida",
    "mobileNumberText": "Número de Móvil",
    "nextText": "Siguiente",
    "onboardingScreenFourSubtitle": "Transfiere sin problemas registros de llamadas entre dispositivos o expórtalos para su custodia y análisis.",
    "onboardingScreenFourTitle": "Importar y Exportar",
    "onboardingScreenOneSubtitle": "Tu aplicación de referencia para gestionar y analizar tus registros de llamadas sin esfuerzo.",
    "onboardingScreenOneTitle": "¡Bienvenido a Logger!",
    "onboardingScreenThreeSubtitle": "Comprende tus patrones de llamadas como nunca antes y obtén información detallada para optimizar tu tiempo.",
    "onboardingScreenThreeTitle": "Analiza Tus Llamadas",
    "onboardingScreenTwoSubtitle": "Busca, filtra y gestiona tus registros de llamadas con una interfaz fluida e intuitiva.",
    "onboardingScreenTwoTitle": "Gestionar Registros de Llamadas",
    "openText": "Abrir",
    "outgoingText": "Saliente",
    "phoneAccountIdText": "ID de Cuenta de Teléfono",
    "platformNameText": "Android",
    "platformText": "plataforma",
    "randomDTRepr": "Vie, 12 Jul 2024 14:15:00",
    "randomMonthAbbr": "Jul",
    "randomMonthName": "Julio",
    "randomWeekdayAbbr": "Vie",
    "randomWeekdayName": "Viernes",
    "refreshText": "Actualizar",
    "rejectedText": "Rechazada",
    "reportIssueButtonText": "Reportar un Problema o Error",
    "resetText": "Restablecer",
    "resetToDefaultText": "Restablecer a Predeterminado",
    "saveText": "Guardar",
    "settingsScreenLabelText": "Ajustes",
    "shareText": "Compartir",
    "showTotalCallDurationText": "Mostrar la duración total de las llamadas",
    "simText": "Nombre de Visualización de SIM",
    "skipText": "Omitir",
    "startImportText": "Iniciar Importación",
    "storagePolicyLabelText": "Política de Almacenamiento",
    "storagePolicyText": "Esta aplicación almacena temporalmente los archivos generados, eliminándolos al salir. Puedes descargar registros de llamadas en la ubicación que elijas. Logger solo accede a los registros de llamadas, lo que garantiza tu privacidad.",
    "supportedFormatInformation": "Ten en cuenta: solo se admite el formato CSV para importar registros de llamadas.",
    "timeText": "Hora",
    "tokenAccordianText": "tokens de formato de fecha y hora",
    "tokensInfoText": "Puedes utilizar los tokens proporcionados para personalizar el formato del nombre de archivo en función de preferencias específicas de fecha y hora.",
    "unknownText": "Desconocido",
    "versionText": "versión",
    "viewText": "Ver",
    "wifiIncomingText": "Wifi Entrante",
    "wifiOutgoingText": "Wifi Saliente",
    "callStatsText": "Estadísticas de Llamadas",
    "callDurationText": "Duración de la Llamada",
    "mostCalledNumberText": "Número Más Llamado",
    "callDirectionAnalysisText": "Análisis de la Dirección de Llamadas",
    "longestCallText": "Llamada Más Larga",
    "topNLongestCalls": "Top {n} Llamadas Más Largas",
    "callText": "Llamar",
    "smsText": "SMS",
    "nothingToDisplayText": "Nada que mostrar",
    "callsMadeText": "Llamadas Realizadas",
    "callsReceivedText": "Llamadas Recibidas",
    "callsMissedText": "Llamadas Perdidas",
    "callsRejectedText": "Llamadas Rechazadas",
    "callsBlockedText": "Llamadas Bloqueadas",
    "averageText": "Promedio",
    "longestText": "Más Largo",
    "totalText": "Total",
    "todayText": "Hoy",
    "yesterdayText": "Ayer",
    "thisMonthText": "Este Mes",
    "pastMonthText": "Mes Pasado",
    "thisYearText": "Este Año",
    "pastYearText": "Año Pasado",
    "allTimeText": "Todo el Tiempo",
    "customText": "Personalizado",
    "startDateText": "Fecha de Inicio",
    "endDateText": "Fecha de Fin",
    "dateRangeText": "Rango de fechas",
    "searchByNumberText": "Número de Teléfono Específico",
    "phoneAccountIdFilterText": "ID de Cuenta de Teléfono",
    "filterByDurationText": "Filtrar por Duración de Llamada",
    "filterByCallTypeText": "Tipo de Llamada",
    "answeredExternallyText": "Contestada Externamente",
    "voiceMailText": "Correo de Voz",
    "exportOpenHintText": "Exportar Abrir",
    "anyText": "Cualquiera",
    "processingFileText": "Procesando archivo",
    "insertingLogsText": "Insertando registros",
    "takingMoreTimeText": "Esto puede tardar más",
    "pleaseWaitText": "Por favor espera",
    "importSuccessMessageText": "Registros de llamadas importados correctamente",
    "failedToUpdateSettingsText": "No se pudo actualizar la configuración. Inténtalo de nuevo más tarde",
    "shareSettingUpdateSuccessMsgText": "Configuración de uso compartido actualizada correctamente.",
    "downloadSettingUpdatedSuccessMsgText": "Configuración de descarga actualizada correctamente.",
    "settingUpdateSuccessMsgText": "Configuración actualizada correctamente.",
    "durationFilterSettingUpdatedSuccessMsgText": "Configuración de filtro de duración actualizada correctamente.",
    "filterByPhoneAccountIdSettingUpdatedSuccessMsgText": "Configuración de filtro por ID de cuenta de teléfono actualizada correctamente.",
    "generalSettingUpdatedSuccessMsgText": "Configuración actualizada correctamente.",
    "importSettingUpdatedSuccessMsgText": "Configuración de importación actualizada correctamente.",
    "exportFieldInfoText": "Información de campos de exportación",
    "csvJsonExportNameField": "Nombre asociado a la entrada del registro de llamadas",
    "csvJsonExportPhoneAccountIdField": "El ID de la cuenta de teléfono asociada con la llamada identifica la cuenta o tarjeta SIM específica utilizada para realizar o recibir la llamada",
    "csvJsonExportCallTypeField": "Tipo de llamada (p. ej., entrante, saliente, perdida)",
    "csvJsonExportNumberField": "Número de teléfono asociado a la entrada del registro de llamadas",
    "csvJsonExportFormattedNumberField": "Número de teléfono formateado, formateado con reglas de formato basadas en el país en el que se encontraba el usuario cuando se realizó o recibió la llamada.",
    "csvJsonExportSimDisplayField": "Nombre de visualización de la tarjeta SIM asociada a la llamada",
    "csvJsonExportTimestampField": "Marca de tiempo (tiempo de época) de la llamada",
    "csvJsonExportDurationField": "Duración de la llamada en segundos",
    "csvJsonExportCachedNumberLabelField": "Etiqueta asociada con el número de teléfono en caché",
    "csvJsonExportCachedNumberTypeField": "El tipo de número en caché (casa, trabajo, etc.) asociado al número de teléfono, si existe.",
    "csvJsonExportCachedMatchedNumberField": "Número de teléfono almacenado o en caché asociado a una entrada de registro de llamadas para una referencia rápida.",
    "exportFieldInfoHintText": "Información de Campos de Exportación",
    "naText": "No intentado",
   
_Heres the german trasnlations_

 "confirmDownloadText": "Download bevestigen",
    "enableDownloadConfirmationText": "Download-Bestätigung aktivieren",
    "mostReceivedNumberText": "Am meisten empfangene Nummer",
    "confirmContactsSyncLabelText": "Bestätigen Sie die Synchronisierung der Kontakte",
    "confirmContactsSyncConfirmationText": "Dieser Prozess scannt Ihre Anrufprotokolle und aktualisiert fehlende Kontaktnamen, indem er sie mit Ihren gespeicherten Kontakten abgleicht. Es wird keine anderen Details in Ihrem Anrufverlauf ändern.",
    "contactsSyncSuccessMessageText": "Kontakte erfolgreich mit den Anrufprotokollen synchronisiert",
    "contactsSyncErrorMessageText": "Fehler bei der Synchronisierung der Kontakte!",
    "contactsPermissionDenied": "Zugriffsberechtigung für Kontakte verweigert!",
    "syncContactsLabelText": "Anrufprotokollkontakte synchronisieren",
    "syncContactsCTAText": "Jetzt synchronisieren"
}

I could translate the false ones if u want

**Comment by Sanmeet007** [comment]
I would greatly appreciate it if you could translate the incorrect parts. Thank you so much—your contribution will benefit others as well. Additionally, if I may suggest, could you consider opening a pull request so I can merge your corrected version with mine for the German text? I'd be happy to guide you through the steps if you're unfamiliar with the process.

**Comment by Stzyxh** [comment]
> I would greatly appreciate it if you could translate the incorrect parts. Thank you so much—your contribution will benefit others as well. Additionally, if I may suggest, could you consider opening a pull request so I can merge your corrected version with mine for the German text? I'd be happy to guide you through the steps if you're unfamiliar with the process.
> 
> 

I'm gonna  open a pull request soon. Thank you for your kind help

**Comment by Sanmeet007** [comment]
@Stzyxh Thanks so much for assisting with the translation! Have a great day. The updated version of the app, including the fixed German translation, is now available for download in the latest release [v2.7.1](https://github.com/logger/tags/v2.7.1).

**Comment by Sanmeet007** [comment]
@Stzyxh Just fixed the software information not in German please update to the new re-release of [v2.7.1](https://github.com/Sanmeet007/logger/releases/tag/v2.7.1)
