### ISSUE TITLE
Showing time of call

### ISSUE THREAD

**Issue by Magneticdud** [Sanmeet007/logger#4]
Thank you for your app, I really like it.

I'm wondering if it's possible to show the time of the call and not only the date

**Comment by Sanmeet007** [comment]
Thank you for your kind words and support! I'm glad you enjoy the app.

I'm excited to share that I've just released an update with some great new features, including the ability to show the time of the call in addition to the date. Also added a toggle to hide the share button.

You can check out the latest release here: [Logger v1.6.0](https://github.com/Sanmeet007/logger/releases/tag/v1.6.0).

Thank you for your feedback and for helping me improve the app for everyone!

**Comment by nev3rfail** [comment]
Hello @Sanmeet007.

Is it possible for the app to honor system locale settings?
App shows 12 hour clock despite system using 24-hour. 
Or maybe you can make it an in-app setting?
