### ISSUE TITLE
Settings option to customise file output format

### ISSUE THREAD

**Issue by caydey** [Sanmeet007/logger#7]
Input box in the settings where the user can specify a custom output format for the exported call logs. The output format should allow for a custom date such as `my_call_log_%y%m%d-%H%M%S`

**Comment by caydey** [comment]
I'll work on this and submit a pull request (hopefully) tonight

**Comment by Sanmeet007** [comment]
@caydey  That would be a fantastic addition! An input box in the settings allowing users to specify a custom output format for the exported call logs, such as my_call_log_%y%m%d-%H%M%S, would definitely enhance the user experience.

If you need any help from me, just comment. I'm looking forward to that PR.

Regarding the UI, I am concerned about maintaining consistency with the overall design (sorry if it feels rude ) anyways, If you need my assistance, I will be just a comment away.

Thank you for considering these suggestions.
